name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Java JDK 11
              uses: actions/setup-java@v4.2.1
              with:
                  java-version: 11
                  distribution: 'temurin'
            - name: Gradle Build Action
              uses: gradle/gradle-build-action@v3.1.0
              with:
                  cache-disabled: true
            - name: Change wrapper permissions
              run: chmod +x ./gradlew
            - name: Detekt
              run: ./gradlew detekt
