name: Detekt Check 
run-name: Check code quality with Detekt 
on: [push]
jobs:
    check-detekt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Java JDK 17
              uses: actions/setup-java@v4.2.1
              with:
                  java-version: 17
                  distribution: 'temurin'
            - name: Setup Gradle 8.2
              uses: gradle/actions/setup-gradle@v3
              with: 
                    gradle-version: 8.2
            - name: Detekt
              run: ./gradlew detekt
