name: detekt-codestyle-check
run-name: Checking codestyle with detekt
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Java JDK 1.8
              uses: actions/setup-java@v4.2.1
              with:
                  java-version: 1.8
                  distribution: 'temurin'

            - name: Gradle Build Action
              uses: gradle/gradle-build-action@v3.1.0
              with:
                  cache-disabled: true

            - name: Detekt
              run: ./gradlew detekt
