name: ktlint Check 
run-name: Check code quality with Ktlint 
on: [push]
jobs:
    check-ktlint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Java JDK 17
              uses: actions/setup-java@v4.2.1
              with:
                  java-version: 17
                  distribution: 'temurin'
            - name: Setup Gradle 8.2
              uses: gradle/actions/setup-gradle@v3
              with: 
                  gradle-version: 8.2
            - name: Change wrapper permissions
              run: chmod +x ./gradlew
            - name: Access API_KEY secret
              env: 
                  API_KEY: ${{ secrets.API_KEY }}
              run: echo API_KEY="$API_KEY" > ./local.properties
            - name: Ktlint
              run: ./gradlew ktlintCheck
